### ISSUE TITLE
log format and git commit for w3c-did events

### ISSUE THREAD

**Issue by jaromil** [dyne/W3C-DID#12]
define log formats to be saved on did changes

one for gource, one human readable...

**Comment by jaromil** [comment]
format (printf stype): `"%s; %s; %c; %s; %s\n"`
contents: `DID.created, DID.ID, new?'A':'M':'D', controller.ID - optional(, SIGN.timestamp)`

'A' = add, new did
'M' = mod, modified did
'D' = del, revoked did

**Comment by jaromil** [comment]
also add git commit to w3c-did-data

**Comment by matteo-cristino** [comment]
Should log files be divided by api's type? For example:
```
api/v1/sandbox/pubkeys-accept.chain -> api_v1_sandbox.log
```
