### ISSUE TITLE
Integrate into Universal Registrar

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/W3C-DID#39]
Next to updating the [universal resolver](https://github.com/danubetech/uni-resolver-driver-did-dns/) we should also integrate into the [Universal Registrar](https://github.com/decentralized-identity/universal-registrar)  - the tool is getting momentum  see the [demo](https://uniregistrar.io/)

**Comment by jaromil** [comment]
For demo purposes we need to introduce an hard-coded `did:dyne:demo` domain that is read only and contains a bunch of ids generated at first boot from known non-random sks.

**Comment by matteo-cristino** [comment]
done in #57

**Comment by matteo-cristino** [comment]
PR opened https://github.com/decentralized-identity/universal-registrar/pull/77, waiting for approval
