### ISSUE TITLE
Improve git commit information

### ISSUE THREAD

**Issue by jaromil** [dyne/W3C-DID#41]
![image](https://user-images.githubusercontent.com/148059/232488047-bce96295-0901-431d-8bfd-6ec1efe784c1.png)
at the moment the information is very raw: the committer name is always same and the comment contains the base64 of the public key of the committer.

We may improve this by:
- use did-controller alias as committer
- include a list of added public keys as comment to commits

and some generic polishing perhaps even emojis

**Comment by matteo-cristino** [comment]
Done in #47
