### ISSUE TITLE
Scrub command to run a local integrity check of all DIDs

### ISSUE THREAD

**Issue by jaromil** [dyne/W3C-DID#7]
The command should be available only locally, perhaps via Makefile

The sysadmin is trusted to know when is the better time to run this command, manually or via cronjob, to avoid overloading server resources.

**Comment by matteo-cristino** [comment]
A first version is implemented in df79ed90236a72815bdb31e056e94bcaecda0b91 with the command `make integrity-check`, this command runs locally. At the moment the path to `data/` is hardcoded in the Makefile. 
TODO: Maybe the latter can be improved by reading the path to data from the `.env` file.
