### ISSUE TITLE
Syntesize test data in sandbox

### ISSUE THREAD

**Issue by jaromil** [dyne/W3C-DID#9]
`make generate-sandbox-did`

**Comment by matteo-cristino** [comment]
This is already implemented and more than 30 `did:dyne:sandbox` are already present on the [explorer](https://explorer.did.dyne.org/). Can we consider this closed or is there something else that i'm missing?

**Comment by jaromil** [comment]
@matteo-cristino should be a script to delete all sandbox and re-populate it with a variable amount of entries
